#############################
# Build System Requirements #
#############################

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = "tests"
addopts = "--cov=pyphenopop --cov-report=xml"
