
name: Deploy

on:
  release:
    types: [published]


jobs:
  deploy:

    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish release distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
